# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/comet/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),comet)

$(call add-radio-file-sha1-checked,radio/abl.img,9b13b04ab00e419f178355e3d07d0d485af89bf0)
$(call add-radio-file-sha1-checked,radio/bl1.img,f189c3adea7722294d0bd15b7ee20fbc719c5467)
$(call add-radio-file-sha1-checked,radio/bl2.img,8a0a5aaff721fce4df22d970ae4262ef6f710d30)
$(call add-radio-file-sha1-checked,radio/bl31.img,80091b7e6a9922b8ab10c038308f46246a511117)
$(call add-radio-file-sha1-checked,radio/gcf.img,7d0d2fd896ea6c17acd2207d8f484c39e4a11c93)
$(call add-radio-file-sha1-checked,radio/gsa.img,5a735f70d56cdbf36f6431f622c4418d6c77c167)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,7c5db0621fc841ccbfbfe20efc210b784ac510c6)
$(call add-radio-file-sha1-checked,radio/ldfw.img,3bf065f92d38f5ea4bfe91f1460c241ce4ce3330)
$(call add-radio-file-sha1-checked,radio/modem.img,902db4e93f82fd822b47488a454df6bb5de4be2b)
$(call add-radio-file-sha1-checked,radio/pbl.img,0dd237b40dd96ca1fd8c276ccdcdb3cfce7c53ff)
$(call add-radio-file-sha1-checked,radio/tzsw.img,8f2fa73cfb265edab9aed69390a4897dba13683c)

endif
